### ISSUE TITLE
Can this be used to upload non-image files, like PDF?

### ISSUE THREAD

**Issue by otang** [upload-io/react-uploader#10]

**Comment by ljwagerfield** [comment]
Hi @otang!

Yes: this component supports all file types 😄 

File previews are supported for images, videos, and PDFs only. (You can disable this.)

Cropping is supported for images only. (You can disable this.)

Other file types (like binaries etc.) will simply appear as file icons in the uploaded file list.

**Comment by otang** [comment]
@ljwagerfield when I was uploading PDF it was converting them to images...

I had no crop settings. Any idea why it would do this? I don't see any config options that would be related

**Comment by ljwagerfield** [comment]
Try using `originalFile.fileUrl` instead of `fileUrl`:

https://github.com/upload-io/react-uploader#the-result

(It sounds like the component is running the PDF via the [Image Processing API](https://upload.io/docs/image-processing-api), just because it can... but it probably shouldn't!)

**Comment by ljwagerfield** [comment]
Which version are you using btw?

For a PDF upload I'd expect the top-level `fileUrl` to be a `/raw/` URL...

**Comment by otang** [comment]
@ljwagerfield yes I think you're right in that it was running the PDF through image processing. I'm using `version "3.22.0"`

I had to switch to a custom component for the file uploads as I wasn't able to stop it from trying to process the documents

**Comment by ljwagerfield** [comment]
Please try again with:

```
{
  "editor": {
    "images": {
      // These are the important settings (to disable PDF previews):
      "crop": false,
      "preview": false
    }
  },
  "layout": "modal",
  "maxFileCount": 1
}
```

The `fileUrl` returned to you by the callback should be a `/raw/` URL, not an `/image/` URL <- if this isn't the case, please let me know, because that would be a bug.
