### ISSUE TITLE
Problem while uploading file into the local directory.

### ISSUE THREAD

**Issue by clonedSemicolon** [upload-io/react-uploader#3]
When I tried to upload the file i want to save into one of my local directory. I added the path into the options. 
But when upload is clicked it shows some error like this 

**You must enable "Folder can be overridden by the uploader"**

**Comment by ljwagerfield** [comment]
Hi @clonedSemicolon!

When you say "local directory", are you referring to a file on your computer?

The `react-uploader` component only supports uploading files to your [Upload.io](https://upload.io) account.

Talk soon!

**Comment by clonedSemicolon** [comment]
Yes, I tried to save the file into the local computer, Thanks for the clarification.
