### ISSUE TITLE
Unable to remove the `Continue` button in `UploadDropzone`

### ISSUE THREAD

**Issue by mooyg** [upload-io/react-uploader#8]
```
<UploadDropzone
          uploader={uploader}
          options={{
            showFinishButton: false,
            maxFileCount: 1,
            mimeTypes: ['image/jpeg', 'image/png'],
            multi: false,
            layout: 'inline',
            showRemoveButton: true,
            editor: { images: { crop: false } },
          }}
          onUpdate={(file) => {
            if (file.length !== 0) {
              generatePhoto(file[0].fileUrl)
            }
          }}
          height="250px"
        />
```
 the continue button just doesn't go away, I wanna use my own button but am unable to

**Comment by ljwagerfield** [comment]
https://codepen.io/upload-js/pen/abQZzbY?editors=0010

The above CodePen is running the same config as you've posted, but it's not displaying a `Continue` button, which means it appears to be behaving as you'd like it to?

Please can you:

1. Confirm if the CodePen (above) is working how you'd like.
2. Confirm which version of `react-uploader` you're using.

Thanks!

**Comment by CyrusVorwald** [comment]
Is it possible to remove the continue button and show a preview?

**Comment by ljwagerfield** [comment]
Hi @CyrusVorwald 👋 

Please can you describe the desired behaviour, step-by-step?

(Ideally with screenshots, and annotations, if possible!)
