### ISSUE TITLE
How to mention path variable in path?

### ISSUE THREAD

**Issue by kirandash** [upload-io/react-uploader#9]
**Requirement**: Currently All my files are getting uploaded to uploads folder.
But I would like to put them in a different folder but with same organisational structure of year, month and date in uploads folder.

Well, I can create the full path on my own using JS but I was curious if there is a way to make use of the existing mechanism of uploads folder to be copied into a new folder.

**What I have tried?**
Settings the `path: '/redesigner.io/{UTC_YEAR}/{UTC_MONTH}/{UTC_DAY}/{UNIQUE_DIGITS_8}{ORIGINAL_FILE_EXT}',`

like above doesn't seem to work

**Comment by ljwagerfield** [comment]
Hi @kirandash 👋 

You'll need to use the following:

```
path: {
  "fileName": "{UNIQUE_DIGITS_8}{ORIGINAL_FILE_EXT}",
  "folderPath": "/redesigner.io/{UTC_YEAR}/{UTC_MONTH}/{UTC_DAY}"
}
```

When you use a `string` for your `path` you can't use path variables, but you can if you use the above `object` instead, see: 

[FilePathDefinition docs](https://upload.io/docs/upload-api/types/FilePathDefinition).

(I appreciate these docs are a little buried away!)

--

p.s. you can also change the default path in the Upload Dashboard by editing your API key's settings, meaning you don't need to specify this in your code.
